export const RSS_FEEDS: { url: string; name: string }[] = [
  // Major wire services
  { url: "https://www.yna.co.kr/rss/news.xml", name: "연합뉴스" },
  { url: "https://feeds.bbci.co.uk/korean/rss.xml", name: "BBC코리아" },
  // National daily newspapers
  { url: "https://www.chosun.com/arc/outboundfeeds/rss/", name: "조선일보" },
  { url: "https://rss.joins.com/joins_news_list.xml", name: "중앙일보" },
  { url: "https://rss.donga.com/total.xml", name: "동아일보" },
  { url: "https://www.hani.co.kr/rss/", name: "한겨레" },
  { url: "https://www.khan.co.kr/rss/rssdata/total_news.xml", name: "경향신문" },
  { url: "https://www.kmib.co.kr/rss/kmibRss.xml", name: "국민일보" },
  { url: "https://www.segye.com/Articles/RssFeeds/", name: "세계일보" },
  { url: "https://www.seoul.co.kr/rss/news-all.xml", name: "서울신문" },
  { url: "https://www.munhwa.com/rss/all.xml", name: "문화일보" },
  { url: "https://www.hankookilbo.com/rss/hankookilbo.xml", name: "한국일보" },
  // Economy newspapers
  { url: "https://www.hankyung.com/feed/all-news", name: "한국경제" },
  { url: "https://www.mk.co.kr/rss/30000001/", name: "매일경제" },
  { url: "https://www.mt.co.kr/rss/news/news_rss.xml", name: "머니투데이" },
  { url: "https://www.fnnews.com/rss/fn_realnews.xml", name: "파이낸셜뉴스" },
  { url: "https://biz.heraldcorp.com/rss/index.xml", name: "헤럴드경제" },
  { url: "https://www.sedaily.com/rss", name: "서울경제" },
  { url: "https://www.asiae.co.kr/rss/all.htm", name: "아시아경제" },
  { url: "https://www.edaily.co.kr/rss/news.xml", name: "이데일리" },
  { url: "https://www.newstomato.com/rss/ReadNews.aspx", name: "뉴스토마토" },
  { url: "https://www.etoday.co.kr/news/rss", name: "이투데이" },
  { url: "https://moneys.mt.co.kr/rss/news/news_rss.xml", name: "머니S" },
  // Broadcast
  { url: "https://www.ytn.co.kr/ln/rss.php", name: "YTN" },
  { url: "http://rss.mbc.co.kr/", name: "MBC" },
  { url: "https://news.kbs.co.kr/rss/rss.xml", name: "KBS" },
  { url: "https://news.sbs.co.kr/news/SectionRssFeed.do?sectionId=01", name: "SBS" },
  { url: "https://fs.jtbc.co.kr/RSS/newsflash.xml", name: "JTBC" },
  { url: "https://www.mbn.co.kr/rss/", name: "MBN" },
  { url: "https://www.tvchosun.com/site/data/rss/rss.xml", name: "TV조선" },
  // Internet news
  { url: "https://www.nocutnews.co.kr/rss/allnews.xml", name: "노컷뉴스" },
  { url: "https://www.ohmynews.com/ohmyrss.aspx", name: "오마이뉴스" },
  { url: "https://www.pressian.com/api/rss", name: "프레시안" },
  { url: "https://www.mediatoday.co.kr/rss/allArticle.xml", name: "미디어오늘" },
  { url: "https://www.vop.co.kr/rss.html", name: "민중의소리" },
  { url: "https://newstapa.org/feed", name: "뉴스타파" },
  { url: "https://www.dailian.co.kr/rss/rss.php", name: "데일리안" },
  { url: "https://www.newspim.com/rss", name: "뉴스핌" },
  { url: "https://www.kukinews.com/rss/index.xml", name: "쿠키뉴스" },
  { url: "https://www.inews24.com/rss/sports_all.xml", name: "아이뉴스24" },
  // Tech
  { url: "https://www.etnews.com/rss/rss.xml", name: "전자신문" },
  { url: "https://www.dt.co.kr/rss/dt.xml", name: "디지털타임스" },
  { url: "https://www.ddaily.co.kr/rss/allArticle.xml", name: "디지털데일리" },
  { url: "https://www.zdnet.co.kr/rss/news.xml", name: "ZDNet Korea" },
  { url: "https://www.bloter.net/feed", name: "블로터" },
  { url: "https://www.boannews.com/media/rss.asp", name: "보안뉴스" },
  // Sports/Entertainment
  { url: "https://www.sportschosun.com/rss/news.xml", name: "스포츠조선" },
  { url: "https://www.sportsworldi.com/rss/allArticle.xml", name: "스포츠서울" },
  { url: "https://www.newsen.com/rss/news.xml", name: "뉴스엔" },
  { url: "https://www.mydaily.co.kr/rss/todaynews.xml", name: "마이데일리" },
  { url: "https://www.starnews.co.kr/rss/allArticle.xml", name: "스타뉴스" },
  { url: "https://www.xportsnews.com/?feed=rss2", name: "엑스포츠뉴스" },
  // Regional - Gyeonggi / Incheon
  { url: "https://www.kyeonggi.com/rss/allArticle.xml", name: "경기신문" },
  { url: "https://www.kgib.co.kr/rss/allArticle.xml", name: "경기일보" },
  { url: "https://www.joongboo.com/rss/S1N1.xml", name: "중부일보" },
  { url: "https://www.incheonilbo.com/rss/allArticle.xml", name: "인천일보" },
  { url: "https://www.kihoilbo.co.kr/rss/allArticle.xml", name: "기호일보" },
  // Regional - Busan / Gyeongnam
  { url: "https://www.busan.com/rss/rss.xml", name: "부산일보" },
  { url: "https://www.kookje.co.kr/rss/allArticle.xml", name: "국제신문" },
  { url: "https://www.gnnews.net/rss/allArticle.xml", name: "경남신문" },
  { url: "https://www.knnews.co.kr/rss/allArticle.xml", name: "경남도민일보" },
  { url: "https://www.ksilbo.co.kr/rss/allArticle.xml", name: "경상일보" },
  // Regional - Daegu / Gyeongbuk
  { url: "https://www.imaeil.com/rss/allArticle.xml", name: "매일신문" },
  { url: "https://www.yeongnam.com/rss/allArticle.xml", name: "영남일보" },
  { url: "https://www.idaegu.co.kr/rss/allArticle.xml", name: "대구신문" },
  { url: "https://www.kyongbuk.co.kr/rss/allArticle.xml", name: "경북일보" },
  { url: "https://www.kbmaeil.com/rss/allArticle.xml", name: "경북매일신문" },
  // Regional - Gangwon
  { url: "https://www.kwnews.co.kr/rss/allArticle.xml", name: "강원일보" },
  { url: "https://www.kado.net/rss/allArticle.xml", name: "강원도민일보" },
  // Regional - Chungcheong
  { url: "https://www.daejonilbo.com/rss/rss.jsp", name: "대전일보" },
  { url: "https://www.cctoday.co.kr/rss/allArticle.xml", name: "충청투데이" },
  { url: "https://www.ccdn.co.kr/rss/allArticle.xml", name: "충청일보" },
  // Regional - Jeolla
  { url: "https://www.jeonbuk.com/rss/allArticle.xml", name: "전북일보" },
  { url: "https://www.sjbnews.com/rss/allArticle.xml", name: "새전북신문" },
  { url: "https://www.gwangju.com/rss/allArticle.xml", name: "광주일보" },
  { url: "https://www.namdonews.com/rss/allArticle.xml", name: "남도일보" },
  { url: "https://www.honam.co.kr/rss/allArticle.xml", name: "전남일보" },
  // Regional - Jeju
  { url: "https://www.jejunews.com/rss/allArticle.xml", name: "제주일보" },
  { url: "https://www.jejusori.net/?skin=rss", name: "제주의소리" },
  { url: "https://www.ihalla.com/rss/allArticle.xml", name: "한라일보" },
  { url: "https://www.jemin.com/rss/allArticle.xml", name: "제민일보" },
  // Business / Finance
  { url: "https://www.businesspost.co.kr/rss/allArticle.xml", name: "비즈니스포스트" },
  { url: "https://www.businesswatch.co.kr/rss/allArticle.xml", name: "비즈니스워치" },
  { url: "https://www.newspim.com/rss/news/finance", name: "뉴스핌금융" },
  { url: "https://www.mediapen.com/rss/allArticle.xml", name: "미디어펜" },
  { url: "https://www.sisajournal.com/rss/allArticle.xml", name: "시사저널" },
  { url: "https://www.sisain.co.kr/?feed=rss2", name: "시사IN" },
  { url: "https://weekly.donga.com/rss", name: "주간동아" },
];
